// gen-uispec.mjs —— 从「设置面板设计方案」文档里解析出设置全集，生成 uispec_gen.go。
//
// 用法: node scripts/gen-uispec.mjs <设计文档.html> <输出.go>
//
// 设计文档本身不在仓库里（它是一份产品文档，不是代码）。文档改动后重跑本脚本即可同步，
// 生成的 uispec_gen.go 随仓库提交 —— 于是构建不依赖这份文档。
// 脚本会逐模块核对「标题上写的三类数量」与「实际解析出来的数量」，对不上就报错退出：
// 解析规则一旦被文档的细微改动带偏，这里会立刻发现，而不是安静地少掉几行。
import fs from 'node:fs';

const SRC = process.argv[2];
const OUT = process.argv[3];
const html = fs.readFileSync(SRC, 'utf8');

const stripTags = (s) => s.replace(/<[^>]*>/g, '');
const unesc = (s) => s
  .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&amp;/g, '&');
const clean = (s) => unesc(stripTags(s)).replace(/\s+/g, ' ').trim();

// 每个模块标题形如: <h3 id="m1">模块 1 界面与外观设置<span class="tag t3">31 项：…</span></h3>
const chunks = html.split(/<h3 id="m\d+">/).slice(1);
const mods = [];
const problems = [];

for (let ch of chunks) {
  // 最后一个模块的片段会一直延伸到文件尾，把正文部分切掉
  ch = ch.split('<section id="p3">')[0];
  const head = /^(.*?)<span class="tag t3">(.*?)<\/span>/.exec(ch);
  if (!head) { problems.push('模块标题解析失败'); continue; }
  const name = clean(head[1]).replace(/^模块\s*\d+\s*/, '').trim();
  const declared = clean(head[2]);
  const want = {};
  let m;
  const cre = /可落地\s*(\d+)|预留\s*(\d+)|参考\s*(\d+)/g;
  while ((m = cre.exec(declared))) {
    if (m[1]) want.land = +m[1];
    if (m[2]) want.reserved = +m[2];
    if (m[3]) want.ref = +m[3];
  }

  const items = [];
  const rows = ch.match(/<tr>[\s\S]*?<\/tr>/g) || [];
  for (const row of rows) {
    const cells = [];
    const re = /<td[^>]*>([\s\S]*?)<\/td>/g;
    let c;
    while ((c = re.exec(row))) cells.push(c[1]);
    if (cells.length < 4) continue;                       // 过滤掉非设置项的表格行
    const mk = /class="tag (t1|t2|t3)"/.exec(cells[0]);
    if (!mk) continue;                                    // 第一格没有分类标记就不是设置项
    const mark = { t1: 'land', t2: 'reserved', t3: 'ref' }[mk[1]];
    const itemName = clean(cells[0].replace(/<span[\s\S]*?<\/span>/g, ''));
    items.push({
      name: itemName,
      desc: clean(cells[1]),
      values: clean(cells[2]),
      effect: clean(cells[3]),
      mark,
    });
  }

  const got = {
    land: items.filter((i) => i.mark === 'land').length,
    reserved: items.filter((i) => i.mark === 'reserved').length,
    ref: items.filter((i) => i.mark === 'ref').length,
  };
  if (want.land !== undefined &&
      (want.land !== got.land || want.reserved !== got.reserved || want.ref !== got.ref)) {
    problems.push(`${name}: 标题写 ${JSON.stringify(want)}，实际解析 ${JSON.stringify(got)}`);
  }
  mods.push({ name, items });
}

if (problems.length) {
  console.error('解析与实际不符，先修脚本：');
  for (const p of problems) console.error('  ' + p);
  process.exit(1);
}

const gq = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
let out = '';
out += '// Code generated by scripts/gen-uispec.mjs from the settings design document. DO NOT EDIT.\n';
out += '//\n';
out += '// 这份清单是设置面板「完整参考视图」的数据源：14 个模块、' +
  mods.reduce((n, m) => n + m.items.length, 0) + ' 条。\n';
out += '// 每条带一个分类标记（land 当前可落地 / reserved 预留 / ref 高阶参考），\n';
out += '// 界面按标记决定是否可操作：只有真正实现了的条目才可操作，其余置灰。\n';
out += '// 哪些条目已经实现，由 uispec_impl.go 里那张手工维护的对照表决定。\n\n';
out += 'package main\n\n';
out += '// uiSpecItem 一条设置项的设计内容。\n';
out += 'type uiSpecItem struct {\n';
out += '\tName   string\n\tDesc   string\n\tValues string\n\tEffect string\n\tMark   string // land / reserved / ref\n}\n\n';
out += '// uiSpecModule 一个设置模块。\n';
out += 'type uiSpecModule struct {\n\tName  string\n\tItems []uiSpecItem\n}\n\n';
out += 'var uiSpecModules = []uiSpecModule{\n';
for (const m of mods) {
  out += `\t{Name: ${gq(m.name)}, Items: []uiSpecItem{\n`;
  for (const i of m.items) {
    out += `\t\t{Name: ${gq(i.name)}, Desc: ${gq(i.desc)}, Values: ${gq(i.values)}, Effect: ${gq(i.effect)}, Mark: ${gq(i.mark)}},\n`;
  }
  out += '\t}},\n';
}
out += '}\n';

fs.writeFileSync(OUT, out, 'utf8');

const total = mods.reduce((n, m) => n + m.items.length, 0);
const sum = (k) => mods.reduce((n, m) => n + m.items.filter((i) => i.mark === k).length, 0);
console.log(`模块 ${mods.length} 个，条目 ${total} 条（可落地 ${sum('land')} / 预留 ${sum('reserved')} / 参考 ${sum('ref')}）`);
console.log('已写出 ' + OUT);
